all: main.cpp List.cpp List.h LnList.h LnList.cpp Node.h Node.cpp
	g++ -c main.cpp
	g++ -c List.h List.cpp
	g++ -c LnList.h LnList.cpp
	g++ -c Node.h Node.cpp
	g++ -Wall -g -std=c++0x -o hw04 main.o List.o LnList.o Node.o
